// apps/wp-lit-html-immer/app.js
import { html, render } from 'lit-html';

import getApp from '../_shared/lit-html/get-App';
import { produce, setAutoFreeze } from 'immer';

setAutoFreeze(false); // for performance

const App = getApp({ html, render });

const test = window.test;

let latestState = test.initialState;
let nextState;
let setStateImmediate;

function setState(state) { // emmulate React'ish setState pattern by deferring states
  nextState = state;
  if (!setStateImmediate) { // avail globally
    setStateImmediate = setImmediate(() => {
      setStateImmediate = null;
      latestState = nextState;
      nextState = null;
      main();
    });
  }
}

const stateManager = (latestState, reducer, action) => produce(latestState, draft => {
  reducer(draft, action);
});

test.dispatch = action => {
  // produce new state (use next if avail, otherwise latest)
  setState(stateManager(nextState || latestState, test.reducer, action));
};

const appEl = document.getElementById('app');

function main() {
  render(App({ useSafeWord: true, state: { data: latestState } }), appEl);
}

main();

// apps/svelte-priority/App.svelte
<script>
	import Child from './Child.svelte';

	export let useSafeWord;
	export let usePriority;
	export let limit;

	const test = window.test;

	let latestState = test.initialState;

	//$: console.log('RENDER APP', latestState.length);

	function setState(newState) { // emmulate React'ish setState pattern by deferring states
		latestState = newState;
	}

	const stateManager = (latestState, reducer, action) => {
		reducer(latestState, action);
		return latestState; // state is mutated in-place, but not returned
	}

	test.dispatch = action => {
		// produce new state (use next if avail, otherwise latest)
		setState(stateManager(latestState, test.reducer, action));
	};

</script>

<div>
	{#each latestState as el, index (el.id)}
		<Child el={el} useSafeWord={useSafeWord} usePriority={usePriority} limit={limit} index={index} />
	{/each}
</div>
