// apps/wp-react-immer/app.js
import React, { createElement } from 'react';
import ReactDOM from 'react-dom';
import getApp from '../_shared/react/get-App';
import { produce, setAutoFreeze } from 'immer';

setAutoFreeze(false); // for performance

const App = getApp(React);

const stateManager = (latestState, reducer, action) => produce(latestState, draft => {
  reducer(draft, action);
});

// legacy React
//ReactDOM.render(createElement(App, { stateManager }), document.getElementById('app'));
// concurrent React
ReactDOM.createRoot(document.getElementById('app')).render(createElement(App, { stateManager }));

// apps/lit-html-immer/app.js
import { html, render } from 'lit-html';

import getApp from '../_shared/lit-html/get-App';
import { produce, setAutoFreeze } from 'immer';

setAutoFreeze(false); // for performance

const App = getApp({ html, render });

const test = window.test;

let latestState = test.initialState;
let nextState;
let setStateImmediate;

function setState(state) { // emmulate React'ish setState pattern by deferring states
  nextState = state;
  if (!setStateImmediate) { // avail globally
    setStateImmediate = setImmediate(() => {
      setStateImmediate = null;
      latestState = nextState;
      nextState = null;
      main();
    });
  }
}

const stateManager = (latestState, reducer, action) => produce(latestState, draft => {
  reducer(draft, action);
});

test.dispatch = action => {
  // produce new state (use next if avail, otherwise latest)
  setState(stateManager(nextState || latestState, test.reducer, action));
};

const appEl = document.getElementById('app');

function main() {
  render(App({ state: { data: latestState } }), appEl);
}

main();
